### ISSUE TITLE
NullPointer Exception

### ISSUE THREAD

**Issue by SirCraftypants** [DecentSoftware-eu/DecentHolograms3#7]
I have no idea why it happened or what triggered it if anything did, it just appeared in my console.

`[06:06:12 WARN]: java.lang.NullPointerException: Cannot invoke "Object.hashCode()" because "key" is null
[06:06:12 WARN]:        at java.base/java.util.concurrent.ConcurrentHashMap.replaceNode(ConcurrentHashMap.java:1111)
[06:06:12 WARN]:        at java.base/java.util.concurrent.ConcurrentHashMap.remove(ConcurrentHashMap.java:1102)
[06:06:12 WARN]:        at DecentHolograms-2.8.1.jar//eu.decentsoftware.holograms.api.utils.color.caching.LruCache.put(LruCache.java:49)
[06:06:12 WARN]:        at DecentHolograms-2.8.1.jar//eu.decentsoftware.holograms.api.utils.color.IridiumColorAPI.process(IridiumColorAPI.java:76)
[06:06:12 WARN]:        at DecentHolograms-2.8.1.jar//eu.decentsoftware.holograms.api.utils.Common.colorize(Common.java:32)
[06:06:12 WARN]:        at DecentHolograms-2.8.1.jar//eu.decentsoftware.holograms.api.holograms.HologramLine.getText(HologramLine.java:326)
[06:06:12 WARN]:        at DecentHolograms-2.8.1.jar//eu.decentsoftware.holograms.api.holograms.HologramLine.update(HologramLine.java:474)
[06:06:12 WARN]:        at DecentHolograms-2.8.1.jar//eu.decentsoftware.holograms.api.holograms.Hologram.lambda$update$6(Hologram.java:666)
[06:06:12 WARN]:        at com.google.common.collect.ImmutableList.forEach(ImmutableList.java:422)
[06:06:12 WARN]:        at DecentHolograms-2.8.1.jar//eu.decentsoftware.holograms.api.holograms.Hologram.update(Hologram.java:666)
[06:06:12 WARN]:        at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
[06:06:12 WARN]:        at DecentHolograms-2.8.1.jar//eu.decentsoftware.holograms.api.holograms.Hologram.updateAll(Hologram.java:674)
[06:06:12 WARN]:        at DecentHolograms-2.8.1.jar//eu.decentsoftware.holograms.api.holograms.Hologram.tick(Hologram.java:316)
[06:06:12 WARN]:        at DecentHolograms-2.8.1.jar//eu.decentsoftware.holograms.api.utils.tick.Ticker.lambda$tick$1(Ticker.java:79)
[06:06:12 WARN]:        at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
[06:06:12 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[06:06:12 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[06:06:12 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)`

**Comment by Andre601** [comment]
Wrong repository?

This is DH3 which is not yet released (nor in any stable state afaik), so your issue, if actually related to DH3, is to be expected as it isn't yet ready for servers...

Also, please use paste sites for sharing errors.

**Comment by SirCraftypants** [comment]
I went to the DecentHolograms github and when i was creating the report, i pressed use blank template and it sent me here. I will close this and go back to the other github but i came here because your other one directed me here.
